experiment:
  name: industrial_robot_ppo
  seed: 42
  device: cuda

environment:
  name: RobotArm-v0
  max_episode_steps: 1000

env:
  arm_dof: 7
  max_episode_steps: 1000
  reward_scale: 1.0
  domain_randomization: true

training:
  algorithm: ppo
  total_timesteps: 1000000
  learning_rate: 3.0e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  checkpoint_freq: 10000
  eval_freq: 5000

model:
  policy_type: MlpPolicy
  hidden_sizes: [256, 256]
  activation: relu

logging:
  wandb: true
  log_interval: 1
  save_interval: 10